spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/util/database/kotlinshop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none # create로 하면 실행할 때마다 테이블 초기화
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace